title:            zgm's Blog
description:      Another ruby developer
url:              # Site url.
links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
  - name:         Feed
    url:          /feed.xml
  - name:         Github
    url:          https://github.com/zhouguangming
    external:     true
  - name:         Twitter
    url:          https://twitter.com/zhouguangming
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
    - tables
